#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment.rb'

class <%=class_name%>TietoFetcherDaemon < Daemon::Base

  @config = YAML.load_file("#{Rails.root}/config/<%=file_name%>.yml")
  @config = @config[Rails.env].to_options

  @sleep_time = @config.delete(:sleep_time) || 60
  def self.start
    puts "Starting <%=class_name%>TietoFetcherDaemon"
    # Add your own receiver object below
    @tieto_fetcher = TietoFetcher.create({:receiver => nil}.merge(@config))

    loop do
      @tieto_fetcher.fetch
      sleep(@sleep_time)
    end
  end

  def self.stop
    puts "Stopping <%=class_name%>TietoFetcherDaemon"
  end

end

<%=class_name%>TietoFetcherDaemon.daemonize
